name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    name: Lint

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Node.js version to 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

  typecheck:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    name: Typecheck

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Node.js version to 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Typecheck
        run: npm run typecheck

  prettier:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    name: Prettier

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Node.js version to 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Prettier
        run: npm run prettier
